### ISSUE TITLE
Upgrade fails (25.0.12-twentyfivezero) over (6.8.112-sixeight)

### ISSUE THREAD

**Issue by gmcpaul** [Intermesh/groupoffice#1253]
Hi again,
still having problem upgrading another machine.

Output of the error:

apt install groupoffice
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be upgraded:
  groupoffice
1 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 77.2 MB of archives.
After this operation, 4,848 kB of additional disk space will be used.
Get:1 http://repo.group-office.com twentyfivezero/main amd64 groupoffice all 25.0.12-twentyfivezero [77.2 MB]
Fetched 77.2 MB in 1s (112 MB/s)       
* synosnap dpkg pre hook check
dumping distro info
(Reading database ... 163041 files and directories currently installed.)
Preparing to unpack .../groupoffice_25.0.12-twentyfivezero_all.deb ...
Determining localhost credentials from /etc/mysql/debian.cnf: succeeded.
apache2_invoke groupoffice prerm: No action required
Unpacking groupoffice (25.0.12-twentyfivezero) over (6.8.112-sixeight) ...
Setting up groupoffice (25.0.12-twentyfivezero) ...
Installing new version of config file /etc/apache2/conf-available/groupoffice.conf ...
Determining localhost credentials from /etc/mysql/debian.cnf: succeeded.
dbconfig-common: writing config to /etc/dbconfig-common/groupoffice.conf
dbconfig-common: flushing administrative password
apache2_invoke groupoffice: no action - configuration was disabled by local admin
Upgrade output will be logged into: log/upgrade/20250408_055330.log

Skipping module caldav because it's not available.
[legacy/calendar] Excuting query: update core_entity set name='CalendarEvent', clientName='CalendarEvent' WHERE name='Event';
legacy/calendar updated from 188 to 189
[legacy/calendar] Excuting query: update core_module set package='community', version=0 where name='calendar'
legacy/calendar updated from 189 to 190

A module was refactored. Rerunning...

Skipping module caldav because it's not available.
[community/calendar] Running callable function
community/calendar updated from 0 to 1
[community/calendar] Running callable function
community/calendar updated from 1 to 2
[community/calendar] Running callable function
community/calendar updated from 2 to 3
[community/calendar] Running callable function
community/calendar updated from 3 to 4
[community/calendar] Excuting query: DELETE f FROM fs_folders f
        LEFT JOIN fs_files fi ON fi.folder_id = f.id
        LEFT JOIN fs_folders ff ON ff.parent_id = f.id
        WHERE 
                 fi.folder_id IS NULL 
                 AND ff.parent_id IS NULL
                 AND f.id IN (SELECT files_folder_id FROM cal_events);
42S02: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'groupoffice.fs_folders' doesn't exist
Query: DELETE f FROM fs_folders f
        LEFT JOIN fs_files fi ON fi.folder_id = f.id
        LEFT JOIN fs_folders ff ON ff.parent_id = f.id
        WHERE 
                 fi.folder_id IS NULL 
                 AND ff.parent_id IS NULL
                 AND f.id IN (SELECT files_folder_id FROM cal_events);
Package: community
Module: calendar
Module installed version: 4
Module source version: 5
ABORTING: Please contact support
dpkg: error processing package groupoffice (--configure):
 installed groupoffice package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 groupoffice
needrestart is being skipped since dpkg has failed
* synosnap dpkg post hook check
dumping distro info
compare distro info
check for file trigger
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by derjoachim** [comment]
It looks as if you have not installed the files module. We are looking into it.

**Comment by mrglobule** [comment]
Good morning,
I cannot be able to open a new issue, so...
I have an issue with the same upgrade and i have this error:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'groupoffice.fs_trash' doesn't exist
can you helping me?

**Comment by mschering** [comment]
Both issues are fixed. We're currently building new versions.

**Comment by mschering** [comment]
Not necessary. The latest version should work.

**Comment by gmcpaul** [comment]
not in my case :(


apt install groupoffice
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be upgraded:
  groupoffice
1 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 77.2 MB of archives.
After this operation, 4,972 kB of additional disk space will be used.
Get:1 http://repo.group-office.com twentyfivezero/main amd64 groupoffice all **25.0.14**-twentyfivezero [77.2 MB]
Fetched 77.2 MB in 1s (125 MB/s)       
* synosnap dpkg pre hook check
dumping distro info
(Reading database ... 163041 files and directories currently installed.)
Preparing to unpack .../groupoffice_25.0.14-twentyfivezero_all.deb ...
Determining localhost credentials from /etc/mysql/debian.cnf: succeeded.
apache2_invoke groupoffice prerm: No action required
Unpacking groupoffice (25.0.14-twentyfivezero) over (6.8.112-sixeight) ...
Setting up groupoffice (25.0.14-twentyfivezero) ...
Installing new version of config file /etc/apache2/conf-available/groupoffice.conf ...
Determining localhost credentials from /etc/mysql/debian.cnf: succeeded.
dbconfig-common: writing config to /etc/dbconfig-common/groupoffice.conf
dbconfig-common: flushing administrative password
apache2_invoke groupoffice: no action - configuration was disabled by local admin
Upgrade output will be logged into: log/upgrade/20250408_094554.log

Skipping module caldav because it's not available.
[legacy/calendar] Excuting query: update core_entity set name='CalendarEvent', clientName='CalendarEvent' WHERE name='Event';
legacy/calendar updated from 188 to 189
[legacy/calendar] Excuting query: update core_module set package='community', version=0 where name='calendar'
legacy/calendar updated from 189 to 190


A module was refactored. Rerunning...

Skipping module caldav because it's not available.
[community/calendar] Running callable function
community/calendar updated from 0 to 1
[community/calendar] Running callable function
community/calendar updated from 1 to 2
[community/calendar] Running callable function
community/calendar updated from 2 to 3
[community/calendar] Running callable function
community/calendar updated from 3 to 4
[community/calendar] Running callable function
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'groupoffice.fs_files' doesn't exist
dpkg: error processing package groupoffice (--configure):
 installed groupoffice package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 groupoffice
needrestart is being skipped since dpkg has failed
* synosnap dpkg post hook check
dumping distro info
compare distro info
check for file trigger
E: Sub-process /usr/bin/dpkg returned an error code (1)****

**Comment by gmcpaul** [comment]
@mschering 
v25.0.14 does not solve the problem.
do you need further information or shall i wait?

**Comment by mrglobule** [comment]
as mschering same issue with 25.0.14

**Comment by mschering** [comment]
Sorry, I'm releasing another version to fix this.

**Comment by mschering** [comment]
Can you send the full output?

**Comment by mschering** [comment]
The new maildomains module that replaces the postfixadmin module uses new tables. You have to use those new tables in the dovecot and postfix.

An option could be to remove dovecot and postfix and all of the configuration files and reinstall it. Warning you might lose manual conguration so perhaps you should back it up:

apt-get purge dovecot dovecot-common postfix

Then /etc/postfix and /etc/dovecot should be gone.

Then reinstall groupoffice-mailserver with

apt-get install groupoffice-mailserver

**Comment by Yaaaxx** [comment]
I have try other things and now it works. But it's a little weird.

For the context, I have a VM with a snapshot on 6.8.112 that i can go back. The folder module is enabled.

The steps :
1. Update from 6.8.112 to 6.8.114
2. Update from 6.8.114 to 25.0.15
3. Error (seems to be the postfixadmin. Was disabled but not uninstalled)

Here, It's the log : 
[20250408-1538.txt](https://github.com/user-attachments/files/19650275/20250408-1538.txt)

I tried a second time, in the meantime 25.0.16 released, with uninstall postfixadmin module.
Steps :
1. Update from 6.8.112 to 6.8.114
2. Uninstall postfixadmin module
3. Update from 6.8.114 to 25.0.16
4. Works

You can look the log too : 
[20250408-1545.txt](https://github.com/user-attachments/files/19650383/20250408-1545.txt)

When I post my issue I tried the same but with uninstall postfixadmin first. Idk what can change. That's why it's weird.
Unfortunately, I lost the log.

Now I have another problem : The calendar tab is not here. Disable and enable the module again change nothing.
Maybe open a new issue ?

**Comment by mschering** [comment]
Maybe a browser cache issue? Any errors in the javascript console?

**Comment by Yaaaxx** [comment]
I tried to delete the cache but change nothing.

Yes I have an error in the console :
```
Uncaught TypeError: GO.email is undefined
    ur http://agenda-test.pibomulti.com/go/modules/community/calendar/views/goui/dist/Index.js:1
    init http://agenda-test.pibomulti.com/go/modules/community/calendar/views/goui/dist/Index.js:1
    register http://agenda-test.pibomulti.com/views/goui/dist/groupoffice-core/script/index.js:2
    <anonymous> http://agenda-test.pibomulti.com/go/modules/community/calendar/views/goui/dist/Index.js:1
Index.js:1:83101
```
The error occur everywhere.

I see that I have the email module installed but not enabled

**Comment by mschering** [comment]
It might be depending on it. Could you try to enable it?

**Comment by Yaaaxx** [comment]
Seems to depends on it. I have enabled the module and now twice appears.
I see any error anymore.
It's good for me. Thanks

**Comment by gmcpaul** [comment]
> The new maildomains module that replaces the postfixadmin module uses new tables. You have to use those new tables in the dovecot and postfix.
> 
> An option could be to remove dovecot and postfix and all of the configuration files and reinstall it. Warning you might lose manual conguration so perhaps you should back it up:
> 
> apt-get purge dovecot dovecot-common postfix
> 
> Then /etc/postfix and /etc/dovecot should be gone.
> 
> Then reinstall groupoffice-mailserver with
> 
> apt-get install groupoffice-mailserver

well but thats not really a upgrade without dataloss or is it?
and in the other case i made on my host the upgrade went without dataloss, so what changed?

**Comment by mschering** [comment]
No it won’t cause any data loss at all! The database and mails will stay of course. It’s just about refreshing the configuration.

**Comment by mschering** [comment]
Yes if you have custom configuration you will have to reapply it as the new package gets its homesite from another db table too. It doesn’t move anything on disk.

**Comment by gmcpaul** [comment]
ok so to confirm: 
after upgrading the groupoffice-mailserver package, ill need to change:

dovecot-groupoffice-sql.conf.ext - only, so i can change the part where mailboxes are stored?
i attached my version which worked on my first test and was not edited

[dovecot-groupoffice-sql.conf.ext.txt](https://github.com/user-attachments/files/19660914/dovecot-groupoffice-sql.conf.ext.txt)

are there other files to be edited?

**Comment by gmcpaul** [comment]
> Yes if you have custom configuration you will have to reapply it as the new package gets its homesite from another db table too. It doesn’t move anything on disk.

thats interesting, because i didnt edit these files at all when i did the upgrade on the first machine
and after updating the mailserver package via "apt install groupoffice-mailserver" my files where not changed and all is working
but that was 6.8.112>25.0.10 🤪

**Comment by mschering** [comment]
I don’t know what’s wrong here. It should upgrade and alter your configuration automatically and work after the upgrade. Now that it’s not I recommend that you backup everything. Then purge dovecot and postfix and reinstall. There are more co dig changes for dkim fts and auto expunge.

**Comment by mschering** [comment]
I just did a fresh install of 6.8 and then an upgrade to 25.0 to double check it all works. It worked fine in my test. Only important thing is to answer "Y" when it asks:


```
Configuration file '/etc/postfix/mysql_virtual_alias_maps.cf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** mysql_virtual_alias_maps.cf (Y/I/N/O/D/Z) [default=N] ? y
Installing new version of config file /etc/postfix/mysql_virtual_alias_maps.cf ...

Configuration file '/etc/postfix/mysql_virtual_mailbox_domains.cf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** mysql_virtual_mailbox_domains.cf (Y/I/N/O/D/Z) [default=N] ? y
Installing new version of config file /etc/postfix/mysql_virtual_mailbox_domains.cf ...

Configuration file '/etc/postfix/mysql_virtual_mailbox_maps.cf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** mysql_virtual_mailbox_maps.cf (Y/I/N/O/D/Z) [default=N] ? y
Installing new version of config file /etc/postfix/mysql_virtual_mailbox_maps.cf ...

```

I've added this as a note to the docs:

https://groupoffice.readthedocs.io/en/latest/upgrade/debian.html#mailserver

**Comment by gmcpaul** [comment]
so i did as you suggested but with the difference that i did not purge but did as follows:

1) refresh the cache with https://server/groupoffice/install 
2) backup /etc/postfix and /etc/dovecot dirs
3) apt install groupoffice-mailserver
3.1) answered with yes as suggested
4) refresh the cache again like 1) ... 
>> all went without errors


check and login to the first mailbox gave me:

GO\Base\Mail\Exception\MailboxNotFound in /usr/share/groupoffice/modules/email/model/Account.php at line 378: Cannot open the folder "INBOX". Please check your email account settings.A2 NO [ SERVERBUG ] Internal error occurred. Refer to server log for more information. [ 2025-04-09 14:12:28 ] ( 0.001 + 0.000 secs)., Last command: A2 SELECT "INBOX"

on all mounted mailboxes, so i knew the mapping was wrong

![Image](https://github.com/user-attachments/assets/202f23c1-b648-42f6-8563-6fb9039d851b)


so i went to the /etc/dovecot dir and checked the conf files there
dovecot-groupoffice-sql.conf.ext - was ok and had the same path as i mapped it to
groupoffice-dict-sql.conf.ext - was ok and new 
groupoffice-domain-owner-sql.conf.ext - was ok and new 
groupoffice-sql.conf.ext - **was** altered to default with the original paths > changed it there 

all other files in the conf.d subpath where ok it seems
so i believe all is good now
@mschering  thank you for your test on your dev machine and updating the docu👍 
i have another topic regarding the dkim feature and rspam dkim but ill create a new case for that
i guess this one can be closed
